language: node_js
node_js:
  - 'stable'
sudo: false
notifications:
  email: false
cache:
  npm: true
  directories:
    - 'node_modules'
script:
  - npm run lint
  - npm run test:coveralls

deploy:
  provider: npm
  on:
    branch: prod
